services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_USERNAME: ${GITHUB_USERNAME}
    volumes:
      - ~/.m2:/root/.m2
    container_name: email-template-service
    restart: unless-stopped
    environment:
      MICRONAUT_ENVIRONMENTS: dev
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      JWT_GENERATOR_SIGNATURE_SECRET: ${JWT_GENERATOR_SIGNATURE_SECRET}
      EMAIL_ADDRESS: ${DEV_EMAIL_ADDRESS}
      EMAIL_TOKEN: ${DEV_EMAIL_TOKEN}
    ports:
      - "8090:8090"
      - "5007:5007"  # Debug port
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=promtail"
      - "service=email-template-service"
    networks:
      - user-web-network
      - observability-stack-network
    # Add .internal DNS aliases to match Kubernetes service names
    extra_hosts:
      - "user-service.internal:user-service"
      - "email-service.internal:email-service"
      - "auth-service.internal:auth-service"
      - "email-template-service.internal:email-template-service"

volumes:
  postgres_data:

networks:
  user-web-network:
    external: true
  observability-stack-network:
    external: true 
