services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_USERNAME: ${GITHUB_USERNAME}
    volumes:
      - ~/.m2:/root/.m2
    container_name: email-template-service
    restart: unless-stopped
    environment:
      MICRONAUT_ENVIRONMENTS: dev
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      JWT_GENERATOR_SIGNATURE_SECRET: ${JWT_GENERATOR_SIGNATURE_SECRET}
      EMAIL_ADDRESS: ${DEV_EMAIL_ADDRESS}
      EMAIL_TOKEN: ${DEV_EMAIL_TOKEN}
      # Service URLs for Docker Compose (use service names)
      USER_SERVICE_URL: http://user-service:8095
      EMAIL_SERVICE_URL: http://email-service:8090
    ports:
      - "8090:8090"
      - "5007:5007"  # Debug port
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=promtail"
      - "service=email-template-service"
    networks:
      - user-web-network
      - observability-stack-network
    # Note: Services communicate using Docker Compose service names
    # The .internal hostnames are handled by Kubernetes service aliases

volumes:
  postgres_data:

networks:
  user-web-network:
    external: true
  observability-stack-network:
    external: true 
