#tag::micronaut[]
micronaut:
  application:
    name: email-template-service
  server:
    port: 8091
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:3000
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    intercept-url-map:
      - pattern: /swagger-ui/**
        access: isAnonymous()
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /v3/api-docs/**
        access: isAnonymous()
      - pattern: /prometheus
        access: isAnonymous()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET}"
        generator:
          refresh-token:
            enabled: true
            secret: "${JWT_GENERATOR_SIGNATURE_SECRET}"
      generator:
        access-token:
          expiration: 360000
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: 1m
  endpoints:
    prometheus:
      enabled: true
      sensitive: false
#end::micronaut[]

#tag::jaeger[]
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1 # <1>
#end::jaeger[]
